### ISSUE TITLE
Paper for OWCAL

### ISSUE THREAD

**Issue by lmullen** [lmullen/legal-modernism#83]

**Comment by kfunk074** [comment]
- [ ] Analyze dates and relative age of cited authorities ([see first proposal here](https://github.com/lmullen/legal-modernism/issues/66#issuecomment-1215868627))
- [ ] Consider if there are meaningful measures of judicial influence from "author" or "judge" tables in CAP--pull judge from list of most cited cases? or try to track counts to particular judges like Lemuel Shaw, James Kent, Joseph Story?
- [ ] Take Wheeler, Practical Law of Slavery (F0105347590): Where else do the cited cases show up? Are they all "property" cases or what other "genre" do they emerge in?

**Comment by kfunk074** [comment]
Not sure if they'll have useful material in time for the paper, but we could see if RAs have analytical ideas if they get a database by mid-month. See #86.

**Comment by kfunk074** [comment]
Working draft can be found here: https://docs.google.com/document/d/1zb-0SGr69mHc6PIlVEwnwWCkXBzvG7vrd6Qxn-M6ILk/edit?usp=sharing

I will flesh it out after other writing deadlines on 2/17.

**Comment by lmullen** [comment]
Another obvious thing to do:

- [ ] Create a co-citation network of cases as seen from the treatises.

**Comment by lmullen** [comment]
- [ ] Create bibliographic coupling network of treatises as linked by the cases they cite

**Comment by lmullen** [comment]
Suggested plan to proceed:

- [ ] Update whitelist (https://github.com/lmullen/legal-modernism/issues/81)
- [ ] Rerun linking over MOML
- [ ] Work on analysis of textbooks
- [ ] Updates to paper visualizations/tables as needed
- [ ] Update single-volume library and regexes (https://github.com/lmullen/legal-modernism/issues/69)
- [ ] Import English Reports database (https://github.com/lmullen/legal-modernism/issues/42)
- [ ] Import Code Reporter database (https://github.com/lmullen/legal-modernism/issues/80)
- [ ] Re-run detection and linking process over MOML, with linking to new databases
- [ ] Update paper visualizations with the new citational databases
- [ ] Attempt coupling/co-citation ideas above and/or canon-cloud idea from https://github.com/lmullen/legal-modernism/issues/66

- [ ] Run detection and linking process over CAP (https://github.com/lmullen/legal-modernism/issues/74)

**Comment by kfunk074** [comment]
Just putting the updates hitlist here for simplicity:

- [ ] Add smoothed curve of age of cases cited in cases
- [ ] Add histogram of age of cases cited in treatises
- [ ] Standardize y-axis on top ten case cite counts (axis of 0 to 20)
- [ ] Update second paragraph count of unique cases cited (currently 326,000)
